#!/bin/bash
# Set API Key here
PUUSH_API_KEY=""

# Puush for Ubuntu/linux
# Owner : Sunmock Yang
# www.sunmock.com
# May 2014
#
# Dependencies:
# - gnome-screenshot
# - curl
# - zenity
# - xclip
# - notify-send
#
# Licence : Beerware
#
# Instructions:
# - Add your puush API key to PUUSH_API_KEY (You can find your API key at http://puush.me/account/settings)
# - Place this file wherever you want (/usr/local/bin)
# - Set up keyboard shortcuts within linux (in Ubuntu it's system settings > keyboard > keyboard shortcuts > custom shortcuts)
#
# 		command			description		(recommended keyboard shortcut)
#		---------------------------------------------------------------
#		puush -c		puush window	(Ctrl + Shift + 2/@)
#		puush -a		puush desktop	(Ctrl + Shift + 3/#)
#		puush -b		area puush		(Ctrl + Shift + 4/$)
#		puush -d		file upload		(Ctrl + Shift + U)
#
#
# Notes:
# - Link(s) will be copied into clipboard and appear in notifications
# - puush curl upload code borrowed from online sources


function getHash () { echo $(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 6 | head -n 1); }

# 1: fileName (Required)
# 2: delete after use (Not required. Default: false)
function puushFile ()
{
	if [[ -z $1 ]]; then
		return
	fi

	url=`curl "https://puush.me/api/up" -# -F "k=$PUUSH_API_KEY" -F "z=waifu" -F "f=@$1" | sed -E 's/^.+,(.+),.+,.+$/\1\n/'`

	if [ "$2" = true ]; then
	    rm $1
	fi

	echo $url
}

function helpText ()
{
  printf "puush for linux\n"
  printf "Created by Sunmock Yang using the puush api\n"
  printf "\n"
  printf "Usage:\n"
  printf "  puush [OPTIONS] [PATH]\n"
  printf "\n"
  printf "OPTIONS:\n"
  printf "  -a			puush entire desktop\n"
  printf "  -b			select area to puush\n"
  printf "  -c			puush current window\n"
  printf "  -d			puush specific file (opens file dialog)\n"
  printf "\n"
  printf "  --help,-h		show this page\n"
  printf "\n"
  printf "PATH:\n"
  printf "  PATH			optional: path of file to puush\n"
}

fileName=""
fileURL=""

if [ -z "$PUUSH_API_KEY" ]; then
  echo "Set the variable PUUSH_API_KEY in $0"
  echo "You can find your API key at http://puush.me/account/settings"

  notify-send -i "$( cd "$( dirname "$0" )" && pwd )/icon.png" "Set the variable PUUSH_API_KEY in $0" "You can find your API key at http://puush.me/account/settings"

  exit 1

elif [ -z "$1" ]; then
	helpText
  exit 1

fi

#Get file to puush and puush it
case "$1" in
	-a)
		echo "Whole Desktop"
			fileName=".puush_$(getHash).png"
			gnome-screenshot -f $fileName
			fileURL=`puushFile "$fileName" true`
		;;

	-b)
		echo "Area"
			fileName=".puush_$(getHash).png"
			gnome-screenshot -a -f $fileName
			fileURL=`puushFile "$fileName" true`
		;;

	-c)
		echo "Window"
			fileName=".puush_$(getHash).png"
			gnome-screenshot -w -f $fileName
			fileURL=`puushFile "$fileName" true`
		;;

	-d)
		echo "File Upload"
			fileName=`zenity --file-selection`
			fileURL=`puushFile "$fileName" false`
		;;

	-h|--help)
		helpText
		exit 1
		;;
		
	*)
		echo "Upload $1"
			fileName=$1
			fileURL=`puushFile "$fileName" false`
		;;
		
esac

if [ ! -z "$fileURL" ]; then
	#Copy link to clipboard, show notification
	echo $fileURL | xclip -selection "clipboard"
	notify-send -i "$( cd "$( dirname "$0" )" && pwd )/icon.png" -t 2000 "puush complete!" "$fileURL"
fi
