#!/bin/bash
function getHash () { echo $(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1); }

# 1: fileName (Required)
# 2: delete after use (Not required. Default: false)
function puushFile ()
{
	echo $1

	if [ "$2" = true ] ; then
	    rm $1
	fi
}

fileName=""

#Get file to puush and puush it
while test $# -gt 0; do
	case "$1" in
		-a)
			echo "Whole Desktop"
				fileName=".tmp_Puush_$(getHash).png"
				#gnome-screenshot -f $fileName
				puushFile $fileName true
			;;
		-b)
			echo "Area"
				fileName=".tmp_Puush_$(getHash).png"
				#gnome-screenshot -f $fileName
				puushFile $fileName true
			;;
		-c)
			echo "Window"
				fileName=".tmp_Puush_$(getHash).png"
				#gnome-screenshot -f $fileName
				puushFile $fileName true
			;;
		-d)
			echo "File Upload"
				fileName=zenity --file-selection
				puushFile $fileName false
			;;
	esac

	shift
done

#Copy link to clipboard

#rm $fileName